url: https://delonmoo.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Anykey
email: delonmoo@outlook.com
description: "摸到就是爽到！"
#"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: DelonMoo
  pic: 1
  position: learner
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/delonmoo
  - title: facebook
    url: #
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: http://github.com/delonmoo

# Postal address (add as many lines as necessary)
address:
  - line: #
  - line: #

# Build settings
markdown: kramdown
permalink: pretty