title: Delon Moo
description: My Personal Blog
author: Delon Moo
logo: /static/img/logo.png
github: https://github.com/delonmoo
about: Here is nothing ~

baseurl: "https://delonmoo.github.io"
url: "https://delonmoo.github.io"

allowsearch: true

disqus_shortname: delonmoo
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
