title: Delon Moo
description: 个人书历
author: Delon Moo
logo: /static/img/logo.png
github: https://github.com/delonmoo
about: 学习者

baseurl: "https://delonmoo.github.io"
url: "https://delonmoo.github.io"

allowsearch: true

disqus_shortname:
google_analytics:

share:
  twitter_username:
  fb_appid: 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
